import { SidebarMenu } from './SidebarMenu';

const links = [
  {
    title: 'Get Started',
    links: [
      { title: 'Introduction', href: '/react' },
      'Kitchen Sink',
      'Installation',
      'Usage',
      { title: 'Usage with Ionic', href: '/react/ionic' },
      { title: 'Usage with Next.js', href: '/react/next-js' },
    ],
  },
  {
    title: 'Utilities',
    links: [
      'Colors',
      'Theme Variants',
      'Hairlines',
      'Safe Areas',
      'Touch Ripple',
      { title: 'useTheme', href: '/react/use-theme' },
      'Fonts',
    ],
  },
  {
    title: 'Components',
    links: [
      {
        title: 'KonstaProvider',
        href: '/react/konsta-provider',
      },
      'App',
      'Action Sheet',
      'Badge',
      'Block',
      'Breadcrumbs',
      'Button',
      'Contacts List',
      'Card',
      'Checkbox',
      'Chip',
      'Data Table',
      'Dialog',
      { title: 'Floating Action Button', href: '/react/fab' },
      'Icon',
      'Link',
      'List',
      'List Button',
      'List Input',
      'List Item',
      'Menu List',
      'Messagebar',
      'Messages',
      'Navbar',
      'Notification',
      'Page',
      { title: 'Panel / Side Panels', href: '/react/panel' },
      'Popover',
      'Popup',
      'Preloader',
      'Progressbar',
      'Radio',
      { title: 'Range Slider', href: '/react/range' },
      'Searchbar',
      { title: 'Segmented Control', href: '/react/segmented' },
      { title: 'Sheet Modal', href: '/react/sheet' },
      'Stepper',
      'Tabbar',
      'Toast',
      'Toggle',
      'Toolbar',
      { title: 'Toolbar Pane', href: '/react/toolbar-pane' },
    ],
  },
];

export const SidebarMenuReact = () => (
  <SidebarMenu links={links} root="react" />
);
